### ISSUE TITLE
クラスやファイルの命名規則について

### ISSUE THREAD

**Issue by momeroku** [parsecmonkey/RepoMainForPy#34]
@parsecmonkey 
クラス，ファイル，関数，変数の命名規則はありますか?

**Comment by parsecmonkey** [comment]
## クラス
- Hoge
  - 最初大文字
## ファイル、関数、変数
- hoge.py hoge_hoge()
  - 全部小文字
  - ハイフンあり

**Comment by momeroku** [comment]
Thank you!
