### ISSUE TITLE
フォントファイルのディレクトリ指定先

### ISSUE THREAD

**Issue by momeroku** [parsecmonkey/RepoMainForPy#38]
@parsecmonkey 

現在，wordcloudの機能ではフォントファイルのパスをWindowsの標準フォント先(C:\Windows\Fonts以下)に指定しています．
これでは，OSが限定されてしまったり，フォントパスを変更しているコンピュータでの実行ができなくなります．

そこで，フリーのフォントファイルを組み込みたいのですが，そのフォントファイルのパスはどこにすれば良いでしょうか?

RepoMainForPyの直下に"data"ディレクトリを作成しておいてよろしいでしょうか?

**Comment by parsecmonkey** [comment]
直下に「font」ディレクトリでいきましょう。

**Comment by momeroku** [comment]
かしこま!
