### ISSUE TITLE
seabornにおけるcmdモジュールの循環参照について

### ISSUE THREAD

**Issue by momeroku** [parsecmonkey/RepoMainForPy#46]
こちらの環境ではseabornで読み込まれている"cmd"モジュールと，RepoMainForPyで読み込まれている，"cmd.py"のモジュールが循環参照します．
ということで，"cmd.py"を別のファイル名に書き換えておいてほしいです．

**Comment by parsecmonkey** [comment]
cmd_seekに変更しました。

**Comment by momeroku** [comment]
thank you :)
